### ISSUE TITLE
can it be used with VideoCrafter1

### ISSUE THREAD

**Issue by lmpeng12** [TianxingWu/FreeInit#10]
can it be used with VideoCrafter1, the github website is https://github.com/AILab-CVC/VideoCrafter.

**Comment by TianxingWu** [comment]
Have not tested it on VideoCrafter1 yet, but you can look into their `ddim_sampling` function [here](https://github.com/AILab-CVC/VideoCrafter/blob/main/lvdm/models/samplers/ddim.py) and refer to the example code [pipeline_animation.py](https://github.com/TianxingWu/FreeInit/blob/master/examples/AnimateDiff/animatediff/pipelines/pipeline_animation.py) and [animate_with_freeinit.py](https://github.com/TianxingWu/FreeInit/blob/master/examples/AnimateDiff/scripts/animate_with_freeinit.py) to add FreeInit into the sampling process.
