### ISSUE TITLE
results issue

### ISSUE THREAD

**Issue by zhw-zhang** [TianxingWu/FreeInit#11]
Hello, I followed the inference operation described on github and used the same model. I got poor results. Is this normal? Can you help me?
![1-A-cat-wearing-sunglasses-and-working-as-a-lifeguard-at](https://github.com/TianxingWu/FreeInit/assets/135094935/3fdf067b-a6ea-499c-9e5d-516587d6663a)

**Comment by TianxingWu** [comment]
Hi @zhw-zhang , I don't think this result is normal. Will release the HuggingFace demo soon, you can have a try and refer to the inference code there. :)

**Comment by zhw-zhang** [comment]
Okay, actually I just changed the relevant paths of the source code. There may be some details in the code that I didn't notice. Looking forward to your HuggingFace demo space.

**Comment by TianxingWu** [comment]
@zhw-zhang Demo is out on HuggingFace: https://huggingface.co/spaces/TianxingWu/FreeInit
Feel free to check it out :)
