### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by duoqingxiaowangzi** [TianxingWu/FreeInit#19]
![image](https://github.com/TianxingWu/FreeInit/assets/117001352/bf13f58b-7d62-4cc1-b0ac-f07175c6db4a)
Hello author, could you please tell me how the addition of pure Gaussian noise and low-frequency information in the figure is implemented in the code? Thank you.

**Comment by TianxingWu** [comment]
Please see pipeline_animation.py [line 590](https://github.com/TianxingWu/FreeInit/blob/410286de018fef339c324e49e894a9cf82824f90/examples/AnimateDiff/animatediff/pipelines/pipeline_animation.py#L590C27-L590C38) and the definition of function freq_mix_3d [line 25](https://github.com/TianxingWu/FreeInit/blob/410286de018fef339c324e49e894a9cf82824f90/examples/AnimateDiff/animatediff/utils/freeinit_utils.py#L25).
