### ISSUE TITLE
Comfyui ?

### ISSUE THREAD

**Issue by Nebuluss** [TianxingWu/FreeInit#3]
Is that possible to implement for comfyui please ?

**Comment by NolenBrolen** [comment]
yes please, this would be awesome to have in comfyUI

**Comment by TianxingWu** [comment]
Myself not very familiar with the Comfyui framework :crying_cat_face:  Currently working on the huggingface demo, would be great if any expert could help with the Comfyui integration :eyes: hopefully

**Comment by ghost** [comment]
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/issues/239

**Comment by Kosinkadink** [comment]
I've now put in an initial implementation of FreeInit in my ComfyUI-AnimateDiff-Evolved nodes. I don't think I'm normalizing the noise properly, but the high-frequency and low-frequency merging works as intended, and it appears to work. I have it exposed as init_type 'DinkInit_v1' - when I revisit this/figure out how to get the normalization of noise to be closer to the diffusers implementations, I'll add an additional init_type to maintain backwards compatibility.

**Comment by TianxingWu** [comment]
> I've now put in an initial implementation of FreeInit in my ComfyUI-AnimateDiff-Evolved nodes. I don't think I'm normalizing the noise properly, but the high-frequency and low-frequency merging works as intended, and it appears to work. I have it exposed as init_type 'DinkInit_v1' - when I revisit this/figure out how to get the normalization of noise to be closer to the diffusers implementations, I'll add an additional init_type to maintain backwards compatibility.

@Kosinkadink Thanks for your work! Much appreciated :)
